import type { Metadata } from "next";
import { Audiowide} from "next/font/google";
import "./globals.css";
import TopNav from "@/components/nav/top-nav";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";

const audiowide = Audiowide({
  variable: "--font-audiowide",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

    <html lang="en">
      <body
        className={`${audiowide.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          >
        <TopNav />
        {children}
        </ThemeProvider>

      </body>
    </html>
    </ClerkProvider>

  );
}
